version: 2
jobs:
  ubuntu-build-and-test:
    docker:
      - image: circleci/python:2.7
      - image: circleci/mysql:5.6
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
    environment:
      CP_MYSQL_TEST_HOST: "127.0.0.1"
      CP_MYSQL_TEST_PASSWORD: ""
      CP_MYSQL_TEST_USER: "root"
    steps:
      - checkout
      - run: sudo add-apt-repository ppa:webupd8team/java && sudo apt update
      - run: sudo apt install oracle-java8-installer
      - run: sudo apt-get install libgstreamer-plugins-base1.0-dev libgtk-3-dev libhdf5-serial-dev
      - run: sudo -H pip install --progress-bar off cython numpy
      - run: sudo -H pip install --find-links https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxpython
      - run: sudo -H pip install --progress-bar off .[test]
      - run: py.test
workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu-build-and-test
